document.getElementById("settings-veiw-memes-block").onclick = function() {
    let is_table = document.getElementById("memes-table").nodeName === "TABLE";
    document.getElementById("memes-table").remove();

    if (is_table) {
        let div = document.getElementById("veiw-memes-block");
        div.insertAdjacentHTML("afterbegin",
            '<ol class="veiw-memes_memes-table" id="memes-table"><caption class="veiw-memes_table-name">Memes</caption><li class="veiw-memes_table-mem">    <a class="veiw-memes_table-mem-reference" href="memes/1.html">        <img class="veiw-memes_table-mem-image" src="image/memes/1.jpg" alt="">    </a></li><li class="veiw-memes_table-mem">    <a class="veiw-memes_table-mem-reference" href="memes/2.html">        <img class="veiw-memes_table-mem-image" src="image/2.jpg" alt="">    </a></li><li class="veiw-memes_table-mem">    <a class="veiw-memes_table-mem-reference" href="memes/3.html">        <img class="veiw-memes_table-mem-image" src="image/3.png" alt="">    </a></li><li class="veiw-memes_table-mem">    <a class="veiw-memes_table-mem-reference" href="memes/4.html">        <img class="veiw-memes_table-mem-image" src="image/memes/4.jpg" alt="">    </a></li><li class="veiw-memes_table-mem">    <a class="veiw-memes_table-mem-reference" href="memes/5.html">        <img class="veiw-memes_table-mem-image" src="image/memes/5.jpg" alt="">    </a></li><li class="veiw-memes_table-mem">    <a class="veiw-memes_table-mem-reference" href="memes/6.html">        <img class="veiw-memes_table-mem-image" src="image/memes/6.jpg" alt="">    </a></li><li class="veiw-memes_table-mem">    <a class="veiw-memes_table-mem-reference" href="memes/7.html">        <img class="veiw-memes_table-mem-image" src="image/memes/7.jpg" alt="">    </a></li><li class="veiw-memes_table-mem">    <a class="veiw-memes_table-mem-reference" href="memes/8.html">        <img class="veiw-memes_table-mem-image" src="image/memes/8.jpg" alt="">    </a></li></ol>');
    } else {
        let div = document.getElementById("veiw-memes-block");
        div.insertAdjacentHTML("afterbegin",
            '<table class="veiw-memes_memes-table" id="memes-table"><caption class="veiw-memes_table-name">Memes</caption><tr class="veiw-memes_table-line">    <th class="veiw-memes_table-mem">        <a class="veiw-memes_table-mem-reference" href="memes/1.html"><img class="veiw-memes_table-mem-image" src="image/1.jpg" alt="">        </a>    </th>    <th class="veiw-memes_table-mem">        <a class="veiw-memes_table-mem-reference" href="memes/2.html"><img class="veiw-memes_table-mem-image" src="image/2.jpg" alt="">        </a>    </th>    <th class="veiw-memes_table-mem">        <a class="veiw-memes_table-mem-reference" href="memes/3.html"><img class="veiw-memes_table-mem-image" src="image/3.jpg" alt="">        </a>    </th>    <th class="veiw-memes_table-mem">        <a class="veiw-memes_table-mem-reference" href="memes/4.html"><img class="veiw-memes_table-mem-image" src="image/4.jpg" alt="">        </a>    </th></tr><tr class="veiw-memes_table-mem">    <th class="veiw-memes_">        <a class="veiw-memes_table-mem-reference" href="memes/5.html"><img class="veiw-memes_table-mem-image" src="image/5.jpg" alt="">        </a>    </th>    <th class="veiw-memes_table-mem">        <a class="veiw-memes_table-mem-reference" href="memes/6.html"><img class="veiw-memes_table-mem-image" src="image/6.jpg" alt="">        </a>    </th>    <th class="veiw-memes_table-mem">        <a class="veiw-memes_table-mem-reference" href="memes/7.html"><img class="veiw-memes_table-mem-image" src="image/7.jpg" alt="">        </a>    </th>    <th class="veiw-memes_table-mem">        <a class="veiw-memes_table-mem-reference" href="memes/8.html"><img class="veiw-memes_table-mem-image" src="image/8.jpg" alt="">        </a>    </th></tr></table>');
    }
}